### ISSUE TITLE
via PHP?

### ISSUE THREAD

**Issue by emresaracoglu** [jmcker/Peer-to-Peer-Cue-System#11]
Hello

Is it possible to send data with PHP?

Thanks

**Comment by jmcker** [comment]
You could certainly serve a website with PHP that allows visitors to use PeerJS. You could even serve this site by changing the file extensions and adding any PHP code that you want.

But to actually send data from your PHP server to a peer is not exactly the main use case of PeerJS or peer-to-peer in general. If all you're looking for is two-way communication between the PHP server and the client, you could check out something like WebSockets or a library like Ratchet that abstracts them for you.
