### ISSUE TITLE
how to have a different 2 laptop with a voice chat?

### ISSUE THREAD

**Issue by gumuruhsspj** [jmcker/Peer-to-Peer-Cue-System#12]
is it peer to peer cue system capability of 
having a voice chat each other?
While the 2 laptops connected on different wifi networks?

**Comment by jmcker** [comment]
There is no voice chat built into this at the moment. It shouldn't be too hard to add. If you look at what's already there and the methods below, you should be able to get it going:

- https://peerjs.com/docs.html#peercall
- https://peerjs.com/docs.html#peeron-call

Every network is different, and you may need a TURN server if the NAT is unfriendly to peer connections. Search [the docs](https://peerjs.com/docs.html) for "Are there any caveats?" and you can see their warning about certain NAT setups. They also offer a free TURN server. I do not have a TURN server configured on this demo, but you can see how to set it in the docs as well.
