### ISSUE TITLE
issues while using in Mobile 

### ISSUE THREAD

**Issue by ttejas123** [jmcker/Peer-to-Peer-Cue-System#15]
I found peerjs able to connect but not able to send data to other peers. 
here i am only include mobile related issues. It's working pretty good at laptops, pc.

**Comment by jmcker** [comment]
Hi @ttejas123 

I'm able to get it working right now on:
- Chrome 88.0.4324.93 / Android 11  <-> same
- Firefox 84.1.4 / Android 11 <-> same (this was a bit finicky with 2 tabs on the same device)
- Chrome 88.0.4324.93 / Android 11<-> Firefox 84.0.2 / Windows 10 Pro 20H2
- Firefox 84.1.4 / Android 11 <-> Firefox 84.0.2 / Windows 10 Pro 20H2

I'm happy to help debug a bit further if I can, but this issue might be more pertinent over on the [peers/peerjs repo](https://github.com/peers/peerjs). 
In either case, it would be helpful to provide some more info about what browser / OS combos you're trying.
