### ISSUE TITLE
Your Examples/demo link seems to have been taken over by a bad actor.

### ISSUE THREAD

**Issue by joeynelson** [jmcker/Peer-to-Peer-Cue-System#16]
One https://peerjs.com/examples.html

The example link goes to:
http://jackmckernan.tk/open-development/peer-to-peer-cue-system/

Following this link takes me to a page that attempts to get me to install an extension.  Seems pretty fishy.

**Comment by jmcker** [comment]
That is fishy indeed... I lost control of that domain recently. I'll see if I can get it updated in the docs.

Thanks for opening the issue.

Edit: A working link is https://jmcker.github.io/Peer-to-Peer-Cue-System/ if you didn't already grab it from the README

**Comment by jmcker** [comment]
Link is updated. Might take a few minutes to propagate. I had to message the Telegram group since there doesn't seem to be a public-facing repo for that page.

Thanks again for spotting and reporting it.
