### ISSUE TITLE
could not get an id from the server peerjs 

### ISSUE THREAD

**Issue by RamyaAshika** [jmcker/Peer-to-Peer-Cue-System#2]
Peer ID is not generating suddenly from yesterday itself and this example is not working.

**Comment by jmcker** [comment]
This has been fixed and is live. PeerJS needed a version bump. See #3 and #4.

**Comment by luapp** [comment]
Hello, I am using PeerJS and it can't get a ID from the server:
```Error:  Error: Could not get an ID from the server.```
This is the code I use to get the ID (it worked one week ago):
```
const peer = new peerjs()
    peer.on("open", (id) => {
      console.log(id)
    })
```
