### ISSUE TITLE
CORS policy: Receiver can't create ID on Demo page

### ISSUE THREAD

**Issue by pReya** [jmcker/Peer-to-Peer-Cue-System#5]
Unfortunately the demo currently does not work. Since the demo website is not using TLS, the user will get a CORS policy error:

`Failed to load resource: the server responded with a status of 504 ()
receive.html:1 Access to XMLHttpRequest at 'https://0.peerjs.com/peerjs/id?ts=15438508918090.3806686527050229' from origin 'http://jackmckernan.tk' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I guess there are two solutions to this:

1. Add a certificate to the website and serve it via https (preferred) or
2. Add `secure: false` to the `new Peer()`call

**Comment by jmcker** [comment]
I've added ```secure: false``` to the Peer creation. Since my current hosting provider does not support installing SSL certs, this is my only option for now.

I couldn't reproduce the error you received prior to adding it, so please let me know if this change resolves the issue or if this was not the root cause.

**Comment by pReya** [comment]
Thanks, Jack. It's working now.

Have you considered hosting this example on GitHub Pages? That'll be free for you and they support free HTTPS.

**Comment by jmcker** [comment]
Switched it over and redirected the old URL. Thanks for the suggestion! That setup was a breeze :+1:
