### ISSUE TITLE
Sender Send button not doing anything

### ISSUE THREAD

**Issue by MuhammadFaizanKhan** [jmcker/Peer-to-Peer-Cue-System#6]
after making successful connect, On sender.html send button is not working. Even i try to log the event s`endButton.onclick` but no log is showing.

**Comment by jmcker** [comment]
Is this still reproducible? If so, which browser are you using?

I think there were some issues with the PeerJS servers the other day, but it appears to have been resolved now.

**Comment by jmcker** [comment]
Closing since I can't reproduce without a bit more info. Feel free to reopen if it's still an issue.
