### ISSUE TITLE
npm run watch is not working 

### ISSUE THREAD

**Issue by Y0geshsharma** [jmcker/Peer-to-Peer-Cue-System#8]
when we try on different laptop that is hosted in a local server there is a media issue

**Comment by jmcker** [comment]
Are you trying to run this example with your own PeerJS server? 

This project doesn't use NPM, so I'm assuming you're referring to running ```npm watch``` within the PeerJS repo.

**Comment by Y0geshsharma** [comment]
No, i have cloned your project and used but it it's working.
Thank you for taking tome to respond to my problem

**Comment by jmcker** [comment]
Can you post any errors that you're receiving or explain more closely what you're trying to do? I'm not sure I follow yet.

**Comment by harshaparjanya** [comment]
@jmcker ,

I am facing the same issue with Nginx server serving the peer JS demo project. The receiver is able to connect and the status stated "connected" but the sender status is blank and it is unable to send messages.

I am using Google Chrome : Version 77.0.3865.90 (Official Build) (64-bit)
and I do not have any error logs in console.

**Comment by jmcker** [comment]
@harshaparjanya were you able to figure out your issue?
